bookBooking/authen/urls.py
from django.urls import path

from authen.views import LoginView, LogoutView, RegisterView


urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
]

bookBooking/bookBooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookings/', include("booking.urls")),
    path('manage/', include("manageBook.urls")),
    path('authen/', include("authen.urls"))
]

bookBooking/booking/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("index/", views.IndexView.as_view(), name="index"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/<int:cart_id>/", views.ConfirmBooking.as_view(),
         name="confirm_booking"),
    path("cart/<int:cart_id>/<int:book_id>",
         views.RemoveBookFromCart.as_view(), name="remove_book"),
    path("index/<int:book_id>", views.BookDetailView.as_view(), name="book-detail"),
    path("history/", views.BorrowHistoryView.as_view(), name="history"),
    path("borrow/", views.BorrowListView.as_view(), name="borrow-list"),
    path("borrow/<int:history_id>", views.BorrowDetailView.as_view(), name="borrow-detail"),
]

bookBooking/booking/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

# Create your models here.


class BookStatus(models.Model):
    status = models.CharField(max_length=10)

    def __str__(self):
        return self.status


class Cart(models.Model):
    member = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Cart of {self.member.first_name}"


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart, related_name='items', on_delete=models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(
        'manageBook.Book', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.book.name} in cart of {self.cart.member.first_name}"


class BorrowBook(models.Model):
    history = models.ForeignKey(
        'booking.BorrowHistory', null=True, blank=True, on_delete=models.CASCADE)
    book = models.ForeignKey(
        'manageBook.Book', on_delete=models.CASCADE, null=True, blank=True)
    queue_date = models.DateTimeField(null=True)
    borrow_date = models.DateField(null=True, blank=True)
    status = models.ForeignKey(BookStatus, default=1, on_delete=models.CASCADE)


class BorrowHistory(models.Model):
    member = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name='borrower')

bookBooking/booking/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.db.models import Q, DurationField
from django.http import HttpRequest
from booking.models import *
from manageBook.models import *
from django.shortcuts import get_object_or_404
from datetime import date, time, datetime
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import F, Count
from datetime import timedelta
from django.urls import reverse

# Create your views here.


class IndexView(View):
    def get(self, request):
        query = request.GET

        if query.get("search"):
            books = Book.objects.filter(
                Q(name__icontains=query.get("search")) |
                Q(author__icontains=query.get("search")) |
                Q(categories__name__icontains=query.get("search"))
            )
        else:
            books = Book.objects.all()

        return render(request, "index.html", {
            "books": books
        })


class BookDetailView(View):
    def get(self, request, book_id):
        book_detail = Book.objects.get(id=book_id)
        cart, created = Cart.objects.get_or_create(member_id=request.user.id)
        book_in_cart = CartItem.objects.filter(
            cart=cart, book=book_detail.id).exists()

        return render(request, "book-detail.html", {
            "book_detail": book_detail,
            "book_in_cart": book_in_cart,
        })

    def post(self, request, book_id):
        # if not request.user.is_authenticated:
        #     return redirect('login')
        book = get_object_or_404(Book, id=book_id)
        cart, created = Cart.objects.get_or_create(member_id=request.user.id)

        book_in_cart = CartItem.objects.filter(cart=cart, book=book).exists()
        if not book_in_cart:
            CartItem.objects.create(cart=cart, book=book)

        return redirect(reverse('book-detail', args=[book.id]))


class CartView(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.view_cart"]

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('login')
        cart, created = Cart.objects.get_or_create(member=request.user)
        items = cart.items.all()

        return render(request, "cart.html", {'items': items, 'cart': cart})


class ConfirmBooking(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.add_borrowbook"]

    def post(self, request, cart_id):
        cart = get_object_or_404(Cart, id=cart_id)
        books_in_cart = CartItem.objects.filter(cart=cart)

        for cart_item in books_in_cart:
            book = cart_item.book

            borrow_history = BorrowHistory.objects.create(member=request.user)

            BorrowBook.objects.create(
                history=borrow_history,
                book=book,
                queue_date=datetime.today(),
                borrow_date=date.today(),
                status=BookStatus.objects.get(id=1)
            )

        cart.items.all().delete()

        return redirect('index')


class RemoveBookFromCart(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.delete_borrowbook"]

    def post(self, request, cart_id, book_id):
        cart = get_object_or_404(Cart, id=cart_id)
        book = get_object_or_404(Book, id=book_id)

        cart_item = CartItem.objects.filter(cart=cart, book=book).first()
        if cart_item:
            cart_item.delete()

        return redirect('cart')


class BorrowHistoryView(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.view_borrowhistory"]

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('login')
        borrow_history = BorrowHistory.objects.filter(member=request.user).annotate(
            returned_date=F('borrowbook__borrow_date') + timedelta(days=7)
        )

        return render(request, "borrow-history.html", {
            'borrow_history': borrow_history
        })


class BorrowDetailView(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.view_borrowbook"]

    def get(self, request, history_id):
        if not request.user.is_authenticated:
            return redirect('login')
        borrow_list = BorrowBook.objects.filter(history__member=request.user, status__id__range=(1, 3), history_id=history_id).annotate(
            days_left=F('borrow_date')+timedelta(days=7)-date.today()
        )

        borrow_list2 = BorrowBook.objects.filter(history__member=request.user, status__id__range=(1, 3), history_id=history_id).annotate(
            return_date=F('borrow_date')+timedelta(days=7)
        )

        if borrow_list.exists():
            borrow_date = borrow_list.first().borrow_date
        else:
            borrow_date = None

        return render(request, "borrow-book-detail.html", {
            'borrow_list': borrow_list,
            'borrow_list2': borrow_list2,
            'borrow_date': borrow_date

        })


class BorrowListView(PermissionRequiredMixin, LoginRequiredMixin, View):
    login_url = '/authen/'
    permission_required = ["booking.view_borrowbook"]

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('login')

        borrow_list = BorrowBook.objects.filter(
            history__member=request.user, status__id__range=(1, 3))
        return render(request, "borrow-book-list.html", {
            'borrow_list': borrow_list,
        })

bookBooking/booking/templates/book-detail.html
{% extends "layout.html" %} {% block page_title %}book-detail{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
    <div class="BookDetail">
      <h1 id="book_detail_title">{{ book_detail.name }}</h1>
      <div class="BookDetail-book-wrapper">
       <div class="book-coverWrapper">
        <img id="book-detailCover" src="https://th.bing.com/th/id/OIP.xONRNGDuga-3ecOyGMje2AAAAA?rs=1&pid=ImgDetMain">
       </div> 
       <div class="book-detail-wrapper">
        <div><span>ผู้แต่ง</span><span class="detail">{{ book_detail.author }}</span></div>
        <div>
          <span>หมวดหนังสือ</span>
          {% for category in book_detail.categories.all %}
            <span class="detail">{{ category.name }}</span>
          {% endfor %}   
          </div>  
        <div><span>สำนักพิมพ์</span><span class="detail">{{ book_detail.publisher }}</span></div>
        <div><span>วัน/เดือน/ปี ที่ตีพิมพ์</span><span class="detail">{{ book_detail.publish_date|date:"Y/m/d" }}</span></div>
        <hr>
        <div>
          <p>เรื่องย่อ</p>
          <p>{{ book_detail.description }}</p>
        </div> 
       </div>
      </div>
      <form id="addToCartForm" method="post" action="{% url 'book-detail' book_detail.id %}">
        {% csrf_token %}
        <div class="button-wrapper">
          {% if book_in_cart %}
            <p>หนังสือเล่มนี้อยู่ในตะกร้าของคุณอยู่แล้ว</p>
          {% else %}
            <button id="addToCart" type="submit">เพิ่มลงตะกร้า</button>
          {% endif %}
        </div>
    </form>
    </div>
    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/borrow-book-detail.html
{% extends "layout.html" %} {% block page_title %}borrow-book-detail{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
        <div class="borrow-list-wrapper">
            <h1 class="booking-title">รายการยืมหนังสือ - {{ borrow_date|date:"Y-m-d" }} </h1>
            {% for borrow in borrow_list %}
            <div class="borrowItem-wrapper">
              <div class="book-coverWrapper">
                <img class="book-cover" id="borrow-book-cover" src="https://th.bing.com/th/id/OIP.xONRNGDuga-3ecOyGMje2AAAAA?rs=1&pid=ImgDetMain">
              </div>
              <div class="borrow-detail-wrapper">
                <div><span class="borrow-book-title">{{borrow.book.name }}</span></div>
                <div>
                  <span>หมวดหนังสือ</span>
                  {% for category in borrow.book.categories.all %}
                    <span class="detail">{{ category.name }}</span>
                  {% endfor %}
                </div>
                {% for return_date in borrow_list2 %}
                <div><span>วัน/เดือน/ปี ทีต้องคืน</span><span class="detail-date">{{ return_date.return_date|date:"Y/m/d" }}</div>
                {% endfor %}
                <div><span>สถานะ</span><span class="borrow-status">{{ borrow.status }}</span></div>
                <div class="days-left"><span>เหลือเวลาอีก</span><span>{{ borrow.days_left }}</span></div>
              </div>
            </div>
            {% empty %}
            <p>คุณไม่มีรายการยืม</p>
            {% endfor %}
        </div>
    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/borrow-book-list.html
{% extends "layout.html" %} {% block page_title %}borrow-book-detail{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
        <div class="borrow-list-wrapper">
            <h1 class="booking-title">รายการยืมหนังสือ</h1>
            {% for borrow in borrow_list %}
            <a class="borrow-listLink" href="{% url 'borrow-detail' borrow.history_id%}">
              <div class="borrowList-wrapper">
                <div class="count-borrow-wrapper">
                </div>
                <div class="borrow-date">
                  <h2>{{ borrow.borrow_date|date:"Y/m/d" }}</h2>
                </div>
                <div class="watch-detail"><p>ดูรายละเอียด -></p></div>
              </div>
            </a>
            {% empty %}
            <p>คุณไม่มีรายการยืม</p>
            {% endfor %}
        </div>
    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/borrow-history.html
{% extends "layout.html" %} {% block page_title %}borrow-history{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
        <div class="history-list-wrapper">
            <h1 class="booking-title">ประวัติการยืมหนังสือ</h1>
            <div class="history-list">    
            {% for history in borrow_history %}
                    {% for book in history.borrowbook_set.all %}
                    <div class="history-wrapper">
                        <div class="historyItems-wrapper">
                            <div class="book-coverWrapper">
                                <img class="book-cover" id="history-book-cover" src="https://th.bing.com/th/id/OIP.xONRNGDuga-3ecOyGMje2AAAAA?rs=1&pid=ImgDetMain">
                            </div>
                            <div class="history-detail-wrapper">
                                <div><p class="history-book-title">{{book.book.name }}</span></div>
                                <div>
                                    <span>หมวดหนังสือ</span>
                                    {% for category in book.book.categories.all %}
                                    <span class="detail">{{ category.name }}</span>
                                    {% endfor %}
                                </div> 
                                <div><span>วัน/เดือน/ปี ทียืม</span><span class="detail-date">{{ book.borrow_date|date:"Y/m/d" }}</span></div>
                                <div><span>วัน/เดือน/ปี ที่คืน</span><span class="detail-date">{{ history.returned_date|date:"Y/m/d" }}</span></div>
                                
                            </div>
                        </div>
                        
                    </div>
                    
                
                    {% endfor %}
                {% empty %}
                <p>คุณไม่มีประวัติการยืม!</p> 
            {% endfor %} 
            </div>
        </div>
    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/cart.html
{% extends "layout.html" %} {% block page_title %}book-list{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
    {% for item in items %}
        <li>
            {{ item.book.name }} - {{ item.book.author }}
            <form method="post" action="{% url 'remove_book' cart.id item.book.id %}">
                {% csrf_token %}
                <button id="removeFromCart" type="submit">เอาหนังสือออก</button>
            </form>
        </li>

        {% empty %}
        <li>Your cart is empty.</li>
        {% endfor %}

    {% if items %}
    <div class="confirm-button">
        <form id="addToCartForm" method="post" action="{% url 'confirm_booking' cart.id %}">
            {% csrf_token %}
            <button id="addToCart" type="submit">ยืนยันการยืม</button>
        </form>
    </div>
    {% endif %}



    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/index.html
{% extends "layout.html" %} {% block page_title %}book-list{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
    <!-- search panel -->
    <form action="{% url 'index' %}">
    <div class="searchPanel">
        <div class="searchBar">
            <input class="input" id="search-bar" type="text" name="search" placeholder="ค้นหาหนังสือ หมวดหนังสือ หรือผู้แต่ง">
        </div>
        <div class="searchBtn">
          <input class="button" id="search-btn" type="submit" value="Search">
      </div>
    </div>
    <!-- book list -->
    
     <div class="bookList">
        {% for book in books %}
        <a class ="book-detailLink" href="{% url 'book-detail' book.id%}">
            <div class="book-wrapper">
                <div class="book-coverWrapper">
                    <img class="book-cover" src="https://th.bing.com/th/id/OIP.xONRNGDuga-3ecOyGMje2AAAAA?rs=1&pid=ImgDetMain">
                </div>
                <div class="detail-wrapper">
                    <h3 class="detail">{{ book.name }}</h3>
                    <p class="detail">{{ book.author }}</p>
                    <div>
                        {% for category in book.categories.all %}
                            <span class="detail" id="detail-category">{{ category.name }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div></div>
            </div>
        </a>
        {% empty %}
        <p>There is no book </p>
        {% endfor %}
    </div>
    
    </form>

    {% endblock content %}
</body>
</html>

bookBooking/booking/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock %}</title>

</head>
<body>
    {% block nav %} {% include 'nav.html' %} {% endblock %}
    <main>
        {% block content %} {% endblock %}
    </main>
</body>
{% block script %}
<link rel="stylesheet" href="{% static '/style_member.css' %}" />
{% endblock %}
</html>

bookBooking/booking/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
    <div>
        <header>
          <nav>
            <a href="{% url 'index' %}" class="web-logo" style="">Name</a>
            <div style="width: 50%;"></div>
            <a href="{% url 'borrow-list' %}">รายการยืมหนังสือ</a>
            <a href="{% url 'history' %}">ประวัติการยืมหนังสือ</a>
            <a href="{% url 'cart' %}">ตะกร้าของฉัน</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">ออกจากระบบ</a>
            {% else %}
                <a href="{% url 'login' %}">เข้าสู่ระบบ</a>
            {% endif %}
          </nav>
        </header>
    </div>
</html>

bookBooking/booking/templates/test.html
{% extends "layout.html" %} {% block page_title %}test{% endblock page_title %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
</head>
<body>
    {% block content %}
    hello world! 2
    {% endblock content %}
</body>
</html>